receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  logging:
    loglevel: debug
  file:
    path: ./sample.json
  carbon:
    endpoint: graphite:2003

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [file, carbon]
